version: '3'
services:
  api:
    build: ./api
    tty: true
    stdin_open: true
    restart: always
    command: fresh
    volumes:
      - ./api/src/app:/go/src/app
    ports:
      - "8080:8080"
    env_file:
      - .env
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3307"
    expose:
      - '3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gohub
      - MYSQL_USER=gohub
      - MYSQL_PASSWORD=gohub_pass
    # volumes:
    #   - ./scripts/db/:/docker-entrypoint-initdb.d/